// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_WEB'] ?? '',
    appId: '1:999471022250:web:5e7fd546d9e4704ec6d0d3',
    messagingSenderId: '999471022250',
    projectId: 'giftimap-57267',
    authDomain: 'giftimap-57267.firebaseapp.com',
    storageBucket: 'giftimap-57267.firebasestorage.app',
    measurementId: 'G-QG5PDQRVXZ',
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_ANDROID'] ?? '',
    appId: '1:999471022250:android:2683900500407a85c6d0d3',
    messagingSenderId: '999471022250',
    projectId: 'giftimap-57267',
    storageBucket: 'giftimap-57267.firebasestorage.app',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_IOS'] ?? '',
    appId: '1:999471022250:ios:5790e23f5ba2a4d4c6d0d3',
    messagingSenderId: '999471022250',
    projectId: 'giftimap-57267',
    storageBucket: 'giftimap-57267.firebasestorage.app',
    iosBundleId: 'com.example.giftimap',
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_IOS'] ?? '',
    appId: '1:999471022250:ios:5790e23f5ba2a4d4c6d0d3',
    messagingSenderId: '999471022250',
    projectId: 'giftimap-57267',
    storageBucket: 'giftimap-57267.firebasestorage.app',
    iosBundleId: 'com.example.giftimap',
  );

  static FirebaseOptions get windows => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_WINDOWS'] ?? '',
    appId: '1:999471022250:web:5a0c42f9d559f2e5c6d0d3',
    messagingSenderId: '999471022250',
    projectId: 'giftimap-57267',
    authDomain: 'giftimap-57267.firebaseapp.com',
    storageBucket: 'giftimap-57267.firebasestorage.app',
    measurementId: 'G-LZ9KLQM1FS',
  );



}